var enableBlocks = true;

/**
 *  @constructor
 *  @extends Floatable
 */

function Block(blockObj) {

	if(!enableBlocks) return;

	if (document.visibilityState === "visible") {
		Floatable.call(this);

		this.width = this.height = 220;

		var volumeSent = parseFloat(blockObj.totalAmount / satoshi).toFixed(2);
		var transactedFees = parseFloat(blockObj.totalFee / satoshi).toFixed(2);

		this.addImage(blockImage, this.width, this.height);
		this.addText('<a href="https://explorer.lisk.io/block/' + blockObj.blockID + '">' +
										'<span class="BlockHeight">Block #' + blockObj.height + '</span>' +
								 '</a><br />' +
								 '<span class="BlockBody">Generated by <strong>' + blockObj.delegate.username + ' </strong><br />' +
								 'Transactions: ' + blockObj.numberOfTransactions + '<br />' +
								 'Volume: ' + volumeSent + ' LSK <br />' +
								 'Fees: ' + transactedFees + ' LSK </span>');
		this.initPosition();
	}

	// Sound
	Sound.playRandomSwell();

	block_count++;
	if (block_count === 1) {
			document.getElementById("waitingForTransactions").style.opacity = "0";
	}
}

extend(Floatable, Block);
